### ISSUE TITLE
Setup the testing framework and the first test

### ISSUE THREAD

**Issue by xdivby0** [dhbw-stg-tinf17a/ase-pda-project#25]
As a developer, I want to have tests, because I want to see if my code works after I made modifications to it.

**Comment by oliver-rudzinski** [comment]
Please make Issue Title less abstract and more descriptive.

**Comment by xdivby0** [comment]
> 
> 
> Please make Issue Title less abstract and more descriptive.

What about the current title, more precise now?

**Comment by oliver-rudzinski** [comment]
lgtm 👍🏼
