### ISSUE TITLE
Add EsLinter to project

### ISSUE THREAD

**Issue by MelZeem** [dhbw-stg-tinf17a/ase-pda-project#29]
🧑🏽‍💻As a developer,
📝I want to be able to use the EsLinter
✅so that all code is clean.

**Comment by oliver-rudzinski** [comment]
I assume that the linter is already included. You need to install ESLint via `npm install --save-dev eslint`.

**Comment by MelZeem** [comment]
Genau das habe ich gemacht. Das war der Sinn des Issues
